format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$fill\
$java\
$nodejs\
$lua\
$python\
$docker_context\
$line_break\
âœ """

[fill]
symbol=" "

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'
